name = "TensorTrainFEM"
uuid = "cb89bf22-489d-11e9-08a2-cb80975f297a"
authors = ["Markus Bachmayr <bachmayr@uni-mainz.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorTrains = "6a7a8bb0-4806-11e9-323f-e9cf5e27521e"
